name: pago-service

services:
  mysql-pago:
    image: mysql:8.4
    container_name: mysql-pago
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PAGO_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PAGO_MYSQL_DATABASE}
    volumes:
      - mysql_pago_data:/var/lib/mysql
    networks:
      - ms-net

  pago:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-pago
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8101:8101"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_URL: http://config-server:7071
    depends_on:
      - mysql-pago
    networks:
      - ms-net

volumes:
  mysql_pago_data:

networks:
  ms-net:
    external: true
